repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0  # adapte la version
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5  # adapte la version
    hooks:
      - id: prettier
